### ISSUE TITLE
Establecer orden

### ISSUE THREAD

**Issue by ramefx** [unix4you2/auto-trading-bot#1]
Error en establecer  orden
![code](https://user-images.githubusercontent.com/12319489/49702373-0f5ddb00-fbbd-11e8-9d05-d640295c3875.png)
![erro](https://user-images.githubusercontent.com/12319489/49702374-0f5ddb00-fbbd-11e8-832f-6c60f3dc5200.png)

**Comment by unix4you2** [comment]
Hola!
Mira la respuesta que te da el servicio web de hitbtc. Bad quantity.

Intenta ajustando el  valor de la variable asociado a la cantidad que deseas transar.

Saludos

**Comment by ramefx** [comment]
Gracias! 
Estaré informado me gustaría subir los cambios que hice se que son pequeños pero espero aportar algo
[z_divisas.zip](https://github.com/unix4you2/auto-trading-bot/files/2663448/z_divisas.zip)

**Comment by unix4you2** [comment]
Siempre son bienvenidos los ajustes.
Se acaban de agregar directamente en el commit 0ce5965a82b98cea141037f8c5a77a4dab504ecf
Gracias @ramefx 

Para futuros aportes mucho mejor si los haces a través de PR para que todo quede a tu nombre.

**Comment by ramefx** [comment]
Tengo nuevos ajustes pero no se que es un PR y como debo hacerlo, el par ETH/TUSD me esta funcionando muy bien comencé con ETH0.01/5TUSD y ahora está en 0.01/10 con dejar 10 posturas a la 7:00 am hora de cdmx

**Comment by unix4you2** [comment]
Saludos @ramefx

No hay problema si no sabes cómo realizar pull requests.  En resúmen un PR
lo que hace es que tu directamente puedas subir mejoras al código fuente
del auto-trading-bot y luego esas mejoras se unen con la rama principal
para que todos se puedan beneficiar.

Si por ahora no sabes hacerlo me las puedes hacer llegar aquí por correo
indicando qué partes del archivo has movido y con eso yo lo ajusto
directamente en el código fuente y lo dejo con una nota de crédito similar
a esta que fue cuando enviaste la mejora la vez pasada:

[image: Screenshot-20190531061617-599x56.png]


A mi me ha ido también bien, a pesar de ser simple el algoritmo me ha
llevado de 4 dólares hace un año a pasar los 1200 dólares.  Es cuestión de
paciencia para que todas las órdenes se evacuen pues hay personas que se
impacientan y las cancelan dejando el vacío de diferencia entre compra y
venta esperada.

Un saludo.


*Mg. John F. Arroyave Gutiérrez*


Construya Apps web y progresivas en minutos con
*Práctico Framework* - *www.practico.org* <http://www.practico.org/>

**Comment by unix4you2** [comment]
![Screenshot-20190531061617-599x56](https://user-images.githubusercontent.com/2445412/58702973-dc76f180-836c-11e9-85c1-3741cbc4bdca.png)
